<a href="https://colab.research.google.com/github/SterlingHayden/Optimized-Schedule-Planner/blob/main/Project_Brecheisen_Jacob_Hayden_Sterling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install -q pyomo
# !apt-get install -y -qq coinor-cbc

# import itertools
import numpy as np
# import pyomo.environ as pyo

# Parameters

In [ ]:
# DASC Data Science Statistics requirements
courses = np.array([
    "ENGL 1013",
    "ENGL 1033",
    "MATH 2554",
    "PHIL 3103",
    "ECON 2143",
    "DASC 1001",
    "DASC 1104",
    "DASC 1204",
    "DASC 2594",
    "DASC 1222",
    "DASC 2103",
    "DASC 2113",
    "DASC 2203",
    "DASC 2213",
    "DASC 3103",
    "DASC 3203",
    "DASC 3213",
    "DASC 4892",
    "DASC 4113",
    "DASC 4123",
    "DASC 4993",
    "MATH 2564",
    "SEVI 2053",
    "STAT 3113",
    "STAT 4373",
    "STAT 4013",
    "STAT 4333",
    "GEOS 1113", # Science state minimum electives (two courses with labs)
    "ENTO 1023", # Science state minimum electives (two courses with labs)
    "MLIT 1003", # Fine Arts state minimum core
    "HIST 2003", # U.S. History and Government state minimum core
    "COMM 1023", # Social Science state minimum core electives
    "HIST 2013", # Social Science state minimum core electives
    "STAT 3013", # Instead of INEG 2314 (Choose from one of these two-course sequences)
    "STAT 3003", # Instead of INEG 2323 (Choose from one of these two-course sequences)
    "STAT 4023", # Elective Data Science Statistics Concentration (Select 9 hours)
    "STAT 5043", # Elective Data Science Statistics Concentration (Select 9 hours)
    "STAT 4033" # Elective Data Science Statistics Concentration (Select 9 hours)
])

# Vector containing course difficulty
difficulty = np.array([
    0.379216, # ENGL 1013
    0.363097, # ENGL 1033
    0.418993, # MATH 2554
    0.536889, # PHIL 3103
    0.530844, # ECON 2143
    0.310055, # DASC 1001
    0.532869, # DASC 1104
    0.507473, # DASC 1204
    0.536302, # DASC 2594
    0.420941, # DASC 1222
    0.474771, # DASC 2103
    0.471402, # DASC 2113
    0.490532, # DASC 2203
    0.469375, # DASC 2213
    0.469980, # DASC 3103
    0.495592, # DASC 3203
    0.441984, # DASC 3213
    0.495429, # DASC 4892
    0.557682, # DASC 4113
    0.571003, # DASC 4123
    0.561626, # DASC 4993
    0.495060, # MATH 2564
    0.419039, # SEVI 2053
    0.512889, # STAT 3113
    0.585332, # STAT 4373
    0.535201, # STAT 4013
    0.570378, # STAT 4333
    0.375381, # GEOS 1113
    0.422439, # ENTO 1023
    0.462482, # MLIT 1003
    0.487732, # HIST 2003
    0.482239, # COMM 1023
    0.483319, # HIST 2013
    0.475559, # STAT 3013
    0.473715, # STAT 3003
    0.557650, # STAT 4023
    0.557326, # STAT 5043
    0.517241 # STAT 4033
])

# Vector containing credit hours
hours = np.array([
    3, # ENGL 1013
    3, # ENGL 1033
    4, # MATH 2554
    3, # PHIL 3103
    3, # ECON 2143
    1, # DASC 1001
    4, # DASC 1104
    4, # DASC 1204
    4, # DASC 2594
    2, # DASC 1222
    3, # DASC 2103
    3, # DASC 2113
    3, # DASC 2203
    3, # DASC 2213
    3, # DASC 3103
    3, # DASC 3203
    3, # DASC 3213
    2, # DASC 4892
    3, # DASC 4113
    3, # DASC 4123
    3, # DASC 4993
    4, # MATH 2564
    3, # SEVI 2053
    3, # STAT 3113
    3, # STAT 4373
    3, # STAT 4013
    3, # STAT 4333
    3, # GEOS 1113
    3, # ENTO 1023
    3, # MLIT 1003
    3, # HIST 2003
    3, # COMM 1023
    3, # HIST 2013
    3, # STAT 3013
    3, # STAT 3003
    3, # STAT 4023
    3, # STAT 5043
    3 # STAT 4033
])

# Matrix containing when courses are offered
offered = np.array([
    # [Spring, Summer, Fall]
    [1, 1, 1], # ENGL 1013
    [1, 0, 1], # ENGL 1033
    [1, 1, 1], # MATH 2554
    [1, 1, 1], # PHIL 3103
    [1, 1, 1], # ECON 2143
    [0, 0, 1], # DASC 1001
    [0, 0, 1], # DASC 1104
    [1, 0, 0], # DASC 1204
    [0, 0, 1], # DASC 2594
    [1, 0, 0], # DASC 1222
    [1, 0, 0], # DASC 2103
    [0, 0, 1], # DASC 2113
    [1, 0, 0], # DASC 2203
    [0, 0, 1], # DASC 2213
    [0, 0, 1], # DASC 3103
    [1, 0, 0], # DASC 3203
    [1, 0, 0], # DASC 3213
    [0, 0, 1], # DASC 4892
    [0, 0, 1], # DASC 4113
    [0, 0, 1], # DASC 4123
    [1, 0, 0], # DASC 4993
    [1, 1, 1], # MATH 2564
    [1, 1, 1], # SEVI 2053
    [1, 0, 0], # STAT 3113
    [1, 0, 0], # STAT 4373
    [0, 0, 1], # STAT 4013
    [1, 0, 0], # STAT 4333
    [1, 1, 1], # GEOS 1113
    [1, 0, 0], # ENTO 1023
    [1, 1, 1], # MLIT 1003
    [1, 1, 1], # HIST 2003
    [1, 0, 1], # COMM 1023
    [1, 1, 1], # HIST 2013
    [1, 1, 1], # STAT 3013
    [1, 0, 1], # STAT 3003
    [1, 0, 0], # STAT 4023
    [1, 1, 1], # STAT 5043
    [0, 0, 1] # STAT 4033
])

# Matrix containing prerequisites
prereqs = np.array([
    # [Course, Prerequisite]
    ["ENGL 1033", "ENGL 1013"],
    ["DASC 1204", "DASC 1104"],
    ["DASC 2594", "MATH 2564"],
    ["DASC 2594", "DASC 1104"],
    ["DASC 1222", "DASC 1104"],
    ["DASC 2103", "DASC 1204"],
    ["DASC 2113", "MATH 2564"],
    ["DASC 2203", "DASC 1204"],
    ["DASC 2213", "DASC 1104"],
    ["DASC 2213", "DASC 1222"],
    ["DASC 3103", "DASC 2594"],
    ["DASC 3103", "DASC 2203"],
    ["DASC 3203", "DASC 2113"],
    ["DASC 3203", "DASC 2594"],
    ["DASC 3213", "DASC 1104"],
    ["DASC 3213", "STAT 3013"],
    ["DASC 3213", "STAT 3003"],
    ["DASC 4892", "DASC 2113"],
    ["DASC 4892", "DASC 3203"],
    ["DASC 4113", "DASC 2103"],
    ["DASC 4113", "DASC 3203"],
    ["DASC 4123", "DASC 1222"],
    ["DASC 4993", "DASC 4892"],
    ["MATH 2564", "MATH 2554"],
    ["SEVI 2053", "DASC 1001"],
    ["SEVI 2053", "DASC 1104"],
    ["STAT 3113", "STAT 3013"],
    ["STAT 4013", "DASC 3213"],
    ["STAT 3013", "MATH 2564"],
    ["STAT 3003", "MATH 2554"],
    ["STAT 4023", "DASC 3213"],
    ["STAT 5043", "STAT 3003"],
    ["STAT 4033", "STAT 3003"]
])

# Matrix containing corequisites
coreqs = np.array([
    # [Course, Corequisite]
    ["DASC 1001", "MATH 2554"],
    ["DASC 4892", "DASC 4123"],
    ["DASC 1104", "DASC 1001"],
    ["DASC 1001", "DASC 1104"],
    ["DASC 2213", "DASC 2113"],
    ["DASC 2113", "DASC 2213"],
    ["DASC 2103", "DASC 2203"],
    ["DASC 2203", "DASC 2103"],
    ["DASC 3203", "DASC 3213"],
    ["DASC 3213", "DASC 3203"],
    ["DASC 4113", "DASC 4123"],
    ["DASC 4123", "DASC 4113"]
])

# Vector containing semesters student won't be in school
blacklist = np.array([
    # [Year #, Semester #]
    [0, 0],
    [4, 2]
])

# Vector containing credit hour limits
hour_limits = np.array([
    12, # Spring
    0, # Summer
    12 # Fall
])

# Transform prereqs and coreqs to use indices instead
prereqs = np.vectorize(lambda x: np.where(courses == x)[0])(prereqs)
coreqs = np.vectorize(lambda x: np.where(courses == x)[0])(coreqs)

# Set maximum number of years
max_years = 5

print(courses)
print(hours)
print(hour_limits)
print(offered)
print(prereqs)
print(coreqs)

['ENGL 1013' 'ENGL 1033' 'MATH 2554' 'PHIL 3103' 'ECON 2143' 'DASC 1001'
 'DASC 1104' 'DASC 1204' 'DASC 2594' 'DASC 1222' 'DASC 2103' 'DASC 2113'
 'DASC 2203' 'DASC 2213' 'DASC 3103' 'DASC 3203' 'DASC 3213' 'DASC 4892'
 'DASC 4113' 'DASC 4123' 'DASC 4993' 'MATH 2564' 'SEVI 2053' 'STAT 3113'
 'STAT 4373' 'STAT 4013' 'STAT 4333' 'GEOS 1113' 'ENTO 1023' 'MLIT 1003'
 'HIST 2003' 'COMM 1023' 'HIST 2013' 'STAT 3013' 'STAT 3003' 'STAT 4023'
 'STAT 5043' 'STAT 4033']
[3 3 4 3 3 1 4 4 4 2 3 3 3 3 3 3 3 2 3 3 3 4 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3]
[12  0 12]
[[1 1 1]
 [1 0 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [1 0 1]
 [1 1 1]
 [1 1 1]
 [1 0 1]
 [1 0 0]
 [1 1 1]
 [0 0 1]]
[[ 1  0]
 [ 7  6]
 [ 8 21]
 [ 8  6]
 [ 9  6]
 [10  7]
 [11 21]
 [12  7]
 [13  6]
 [13  9]
 [14  8]
 [14

In [ ]:
model = pyo.ConcreteModel()

In [ ]:
course_idx = range(len(courses)) # Index for courses
sem_idx = range(offered.shape[1]) # Index for semesters
year_idx = range(max_years) # Index for years
prereq_idx = range(prereqs.shape[0]) # Index for prereqs
coreq_idx = range(coreqs.shape[0]) # Index for coreqs

when_offered = {(i, j): offered[i][j] for i, j in itertools.product(course_idx, sem_idx)} # Dictionary containing when courses are offered
difficulty = {i: difficulty[i] for i in course_idx} # Dictionary containing course difficulty
credit_hours = {i: hours[i] for i in course_idx} # Dictionary containing credit hours
hour_limits = {i: hour_limits[i] for i in sem_idx} # Dictionary containing credit hour limits
prereqs = {(i, j): prereqs[i][j] for i, j in itertools.product(prereq_idx, range(2))} # Dictionary containing prerequisites
coreqs = {(i, j): coreqs[i][j] for i, j in itertools.product(coreq_idx, range(2))} # Dictionary containing corequisites

print(course_idx)
print(sem_idx)
print(year_idx)
print(prereq_idx)
print(coreq_idx)

print(when_offered)
print(difficulty)
print(credit_hours)
print(hour_limits)
print(prereqs)
print(coreqs)

range(0, 38)
range(0, 3)
range(0, 5)
range(0, 33)
range(0, 12)
{(0, 0): 1, (0, 1): 1, (0, 2): 1, (1, 0): 1, (1, 1): 0, (1, 2): 1, (2, 0): 1, (2, 1): 1, (2, 2): 1, (3, 0): 1, (3, 1): 1, (3, 2): 1, (4, 0): 1, (4, 1): 1, (4, 2): 1, (5, 0): 0, (5, 1): 0, (5, 2): 1, (6, 0): 0, (6, 1): 0, (6, 2): 1, (7, 0): 1, (7, 1): 0, (7, 2): 0, (8, 0): 0, (8, 1): 0, (8, 2): 1, (9, 0): 1, (9, 1): 0, (9, 2): 0, (10, 0): 1, (10, 1): 0, (10, 2): 0, (11, 0): 0, (11, 1): 0, (11, 2): 1, (12, 0): 1, (12, 1): 0, (12, 2): 0, (13, 0): 0, (13, 1): 0, (13, 2): 1, (14, 0): 0, (14, 1): 0, (14, 2): 1, (15, 0): 1, (15, 1): 0, (15, 2): 0, (16, 0): 1, (16, 1): 0, (16, 2): 0, (17, 0): 0, (17, 1): 0, (17, 2): 1, (18, 0): 0, (18, 1): 0, (18, 2): 1, (19, 0): 0, (19, 1): 0, (19, 2): 1, (20, 0): 1, (20, 1): 0, (20, 2): 0, (21, 0): 1, (21, 1): 1, (21, 2): 1, (22, 0): 1, (22, 1): 1, (22, 2): 1, (23, 0): 1, (23, 1): 0, (23, 2): 0, (24, 0): 1, (24, 1): 0, (24, 2): 0, (25, 0): 0, (25, 1): 0, (25, 2): 1, (26, 0): 1, (26, 1): 0, (26, 2

# Model

In [ ]:
model.course_idx = pyo.Set(initialize=course_idx) # Index for courses
model.sem_idx = pyo.Set(initialize=sem_idx) # Index for semesters
model.year_idx = pyo.Set(initialize=year_idx) # Index for years
model.prereq_idx = pyo.Set(initialize=prereq_idx) # Index for prereqs
model.coreq_idx = pyo.Set(initialize=coreq_idx) # Index for coreqs

In [ ]:
model.when_offered = pyo.Param(model.course_idx, model.sem_idx, initialize=when_offered) # Parameter containing when courses are offered
model.difficulty = pyo.Param(model.course_idx, initialize=difficulty) # Parameter containing course difficulty
model.credit_hours = pyo.Param(model.course_idx, initialize=credit_hours) # Parameter containing credit hours
model.hour_limits = pyo.Param(model.sem_idx, initialize=hour_limits) # Parameter containing credit hour limits
model.prereqs = pyo.Param(model.prereq_idx, range(2), initialize=prereqs) # Parameter containing prerequisites
model.coreqs = pyo.Param(model.coreq_idx, range(2), initialize=coreqs) # Parameter containing corequisites

In [ ]:
model.semesters = pyo.Var(model.course_idx, model.year_idx, model.sem_idx, domain=pyo.Binary) # Decision variable for period/semester taken
model.penalty = pyo.Var(model.year_idx, model.sem_idx, domain=pyo.NonNegativeReals) # Decision variable implementing penalty for course hour limits

Course value mathematical formulation:

$$f(\bf{X}, i) = \sum_{j=1}^b \sum_{k=1}^c \left[\bf{X}_{ijk}\left(j + \frac{1}{c - k + 2}\right)\right]$$

Objective function mathematical formulation:

$$\min_{\bf{X}, \bf{P}} \sum_{j=1}^b \sum_{k=1}^c \bf{P}_{jk}$$

In [ ]:
# Calculate value used to compare courses
course_val = lambda model, course_idx: sum(model.semesters[(course_idx, i, j)] * (i + 1 / (len(model.sem_idx) - j + 1) + 1) for i, j in itertools.product(model.year_idx, model.sem_idx))

# Minimize time over semester credit hour limits
obj_rule = lambda model: sum(model.penalty[(i, j)] for i, j in itertools.product(model.year_idx, model.sem_idx))
model.obj = pyo.Objective(rule=obj_rule, sense=pyo.minimize)

Offered rule constraint mathematical formulation:

$$\bf{X}_{ijk} \le \bf{O}_{ik}, \forall i = 1, 2, ..., a, \forall j = 1, 2, ..., b, \forall k = 1, 2, ..., c$$

In [ ]:
# Course must be offered in this semester
offered_rule = lambda model, course_idx, year_idx, sem_idx: model.semesters[(course_idx, year_idx, sem_idx)] <= model.when_offered[(course_idx, sem_idx)]
model.offered_rule = pyo.Constraint(model.course_idx, model.year_idx, model.sem_idx, rule=offered_rule)

Semester rule constraint mathematical formulation:

$$\sum_{j=1}^b \sum_{k=1}^c \bf{X}_{ijk} = 1, \forall i = 1, 2, ..., a$$

In [ ]:
# Must take course during one semester
semester_rule = lambda model, course_idx: sum(model.semesters[(course_idx, i, j)] for i, j in itertools.product(model.year_idx, model.sem_idx)) == 1
model.semester_rule = pyo.Constraint(model.course_idx, rule=semester_rule)

Hours rule constraint mathematical formulation:

$$\bf{P}_{jk} \ge \sum_{i=1}^a \bf{h}_i\bf{X}_{ijk} - \bf{l}_k, \forall j = 1, 2, ..., b, \forall k = 1, 2, ..., c$$

In [ ]:
# Try not to exceed credit hour limits
hours_rule = lambda model, year_idx, sem_idx: model.penalty[(year_idx, sem_idx)] >= sum(model.credit_hours[i] * model.semesters[(i, year_idx, sem_idx)] for i in model.course_idx) - model.hour_limits[sem_idx]
model.hours_rule = pyo.Constraint(model.year_idx, model.sem_idx, rule=hours_rule)

Blacklist rule constraint mathematical formulation:

$$\bf{X}_{ijk} = 0, \forall i = 1, 2, ..., a, \forall (j, k) \in \bf{B}$$

In [ ]:
# Cannot take classes during blacklisted semester
model.blacklist_rule = pyo.ConstraintList()

# Loop over each course and blacklisted semester
for i, row in itertools.product(model.course_idx, blacklist):
  # Add a constraint that the blacklisted semester must be 0
  model.blacklist_rule.add(expr=(model.semesters[(i, row[0], row[1])] == 0))

Difficulty rule constraint mathematical formulation:

$$\sum_{i=1}^a \bf{d}_i\bf{X}_{ij_1k} \le \sum_{i=1}^a \bf{d}_i\bf{X}_{ij_2k}, \forall (j_1, k) \notin \bf{B}, (j_2, k) \notin \bf{B}, j_1 < j_2$$

In [ ]:
# Difficulty must increase on a yearly basis
model.difficulty_rule = pyo.ConstraintList()

# Loop over every semester in every year combo to make sure difficulty increases across years for each semester
for (y1, y2), j in itertools.product(itertools.combinations(model.year_idx, 2), model.sem_idx):
  # Check to make sure neither semester is blacklisted
  if not [y1, j] in blacklist.tolist() and not [y2, j] in blacklist.tolist():
    # Add a constraint that the total difficulty for this semester must be greater next year
    model.difficulty_rule.add(expr=(
        sum(model.difficulty[i] * model.semesters[(i, y1, j)] for i in model.course_idx)
        <=
        sum(model.difficulty[i] * model.semesters[(i, y2, j)] for i in model.course_idx)
    ))

Prerequisite rule constraint mathematical formulation:

$$f(\bf{R}_{m0}) \ge f(\bf{R}_{m1}) + \epsilon, \forall m = 1, 2, ..., d$$

Corequisite rule constraint mathematical formulation:

$$f(\bf{C}_{n0}) \ge f(\bf{C}_{n1}), \forall n = 1, 2, ..., e$$

In [ ]:
# Create sufficiently small error term because strict inequalities are not allowed
epsilon = .001

# Course must come after its prerequisites and with/after its corequisites
prereq_rule = lambda model, prereq_idx: course_val(model, model.prereqs[(prereq_idx, 0)]) >= course_val(model, model.prereqs[(prereq_idx, 1)]) + epsilon
coreq_rule = lambda model, coreq_idx: course_val(model, model.coreqs[(coreq_idx, 0)]) >= course_val(model, model.coreqs[(coreq_idx, 1)])

model.prereq_rule = pyo.Constraint(model.prereq_idx, rule=prereq_rule)
model.coreq_rule = pyo.Constraint(model.coreq_idx, rule=coreq_rule)

# Solution

In [ ]:
opt = pyo.SolverFactory("cbc")
opt.solve(model)

{'Problem': [{'Name': 'unknown', 'Lower bound': 19.0, 'Upper bound': 19.0, 'Number of objectives': 1, 'Number of constraints': 118, 'Number of variables': 285, 'Number of binary variables': 570, 'Number of integer variables': 570, 'Number of nonzeros': 13, 'Sense': 'minimize'}], 'Solver': [{'Status': 'ok', 'User time': -1.0, 'System time': 0.21, 'Wallclock time': 0.32, 'Termination condition': 'optimal', 'Termination message': 'Model was solved to optimality (subject to tolerances), and an optimal solution is available.', 'Statistics': {'Branch and bound': {'Number of bounded subproblems': 0, 'Number of created subproblems': 0}, 'Black box': {'Number of iterations': 0}}, 'Error rc': 0, 'Time': 0.3717536926269531}], 'Solution': [OrderedDict([('number of solutions', 0), ('number of solutions displayed', 0)])]}

In [ ]:
for i, j, k in itertools.product(model.course_idx, model.year_idx, model.sem_idx):
  if pyo.value(model.semesters[(i, j, k)]):
    print(
        i,
        courses[i],
        ["Spring", "Summer", "Fall"][k],
        2023 + j,
        sep="\t"
    )

0	ENGL 1013	Fall	2023
1	ENGL 1033	Fall	2024
2	MATH 2554	Fall	2023
3	PHIL 3103	Spring	2024
4	ECON 2143	Fall	2024
5	DASC 1001	Fall	2023
6	DASC 1104	Fall	2023
7	DASC 1204	Spring	2025
8	DASC 2594	Fall	2025
9	DASC 1222	Spring	2025
10	DASC 2103	Spring	2026
11	DASC 2113	Fall	2025
12	DASC 2203	Spring	2026
13	DASC 2213	Fall	2025
14	DASC 3103	Fall	2026
15	DASC 3203	Spring	2026
16	DASC 3213	Spring	2026
17	DASC 4892	Fall	2026
18	DASC 4113	Fall	2026
19	DASC 4123	Fall	2026
20	DASC 4993	Spring	2027
21	MATH 2564	Fall	2024
22	SEVI 2053	Spring	2024
23	STAT 3113	Spring	2027
24	STAT 4373	Spring	2027
25	STAT 4013	Fall	2026
26	STAT 4333	Spring	2027
27	GEOS 1113	Spring	2026
28	ENTO 1023	Spring	2024
29	MLIT 1003	Fall	2024
30	HIST 2003	Summer	2026
31	COMM 1023	Fall	2026
32	HIST 2013	Spring	2024
33	STAT 3013	Spring	2025
34	STAT 3003	Spring	2025
35	STAT 4023	Spring	2027
36	STAT 5043	Summer	2027
37	STAT 4033	Fall	2025
